### ISSUE TITLE
Where the fuck are my credits at? Skids.

### ISSUE THREAD

**Issue by Elb1to** [thewsomeestgamer/SoupPvP#1]
Nice one skids.
https://github.com/Elb1to/SoupPvP

**Comment by CoOwner** [comment]
> Nice one skids.
> https://github.com/Elb1to/SoupPvP

One simple credit would do good but nah you yoinked his shit 😭😭

**Comment by Elb1to** [comment]
Also, good job violating the license on my shit
https://github.com/Elb1to/SoupPvP/blob/master/LICENSE

**Comment by DevDrizzy** [comment]
This is just ridiculous 😆

**Comment by steamworksmc** [comment]
🤦

**Comment by brew600** [comment]
lmfaoo

**Comment by Elb1to** [comment]
Issue solved

**Comment by thewsomeestgamer** [comment]
Everything has been solved I added his credits as i was sent this by someone else and had no full idea that it wasn't forked and i was told that it was fully changed just some of his code was used.

**Comment by ItzBunniYT** [comment]
> Everything has been solved I added his credits as i was sent this by someone else and had no full idea that it wasn't forked and i was told that it was fully changed just some of his code was used.

biggest fucking cap ever

**Comment by idiol** [comment]
LOL

**Comment by KaboomB52** [comment]
lol never said that just said i used elb1to's base and worked off that lmao u also said u weren't gonna make it public

**Comment by Elb1to** [comment]
You had to keep the fucking credits and all the original in the code regardless of that. It doesn't matter if it was going to be private or not, that doesn't give you any rights to remove crediting to the original author, much less comments LMAO
